export const LOGIN_TO_FACEBOOK = 'LOGIN_TO_FACEBOOK'
export const CURRENT_GAME = 'CURRENT_GAME'
export const CHANGE_CURRENT_GIF = 'CHANGE_CURRENT_GIF'
export const DISPLAY_ANSWERS = 'DISPLAY_ANSWERS'
